# Generated by Django 5.0.4 on 2024-05-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('eage', models.IntegerField()),
                ('ename', models.CharField(max_length=20)),
                ('esalary', models.IntegerField()),
            ],
        ),
    ]
