# Generated by Django 5.0.4 on 2024-05-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=15)),
                ('age',models.ImageField()),
                ('email',models.CharField(max_length=20)),

            ],
        ),
    ]
