# Generated by Django 5.0.4 on 2024-05-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
                ('sloc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbrand', models.CharField(max_length=20)),
                ('cmodel', models.CharField(max_length=20)),
                ('ctype', models.CharField(max_length=20)),
                ('showroom', models.ManyToManyField(to='work3.showroom')),
            ],
        ),
    ]
