# Generated by Django 5.0.4 on 2024-05-21 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbrand', models.CharField(max_length=20)),
                ('cmodel', models.CharField(max_length=20)),
                ('ctype', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=20)),
                ('dadd', models.CharField(max_length=20)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='work1.car')),
            ],
        ),
    ]
